from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from datetime import datetime

OUTPUT_PATH = "/workspace/Disaster_Relief_Management_Project_Report.docx"


def add_heading(doc: Document, text: str, level: int = 1):
    p = doc.add_heading(text, level=level)
    return p


def add_paragraph(doc: Document, text: str, bold: bool = False, italic: bool = False):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.bold = bold
    run.italic = italic
    p.paragraph_format.space_after = Pt(6)
    return p


def add_bullets(doc: Document, items):
    for item in items:
        p = doc.add_paragraph(style='List Bullet')
        p.add_run(item)


def add_numbered(doc: Document, items):
    for item in items:
        p = doc.add_paragraph(style='List Number')
        p.add_run(item)


def add_page_break(doc: Document):
    doc.add_page_break()


def add_header_footer(doc: Document):
    section = doc.sections[0]
    header = section.header
    header_p = header.paragraphs[0]
    header_p.text = "Disaster Relief Management System — Project Report"
    header_p.alignment = WD_ALIGN_PARAGRAPH.CENTER


def add_cover_page(doc: Document):
    title = doc.add_paragraph()
    title_run = title.add_run("Disaster Relief Management System")
    title_run.bold = True
    title_run.font.size = Pt(28)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    subtitle = doc.add_paragraph()
    subtitle_run = subtitle.add_run("Comprehensive Project Report")
    subtitle_run.font.size = Pt(16)
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER

    meta = doc.add_paragraph()
    meta_run = meta.add_run(f"Generated on {datetime.now().strftime('%Y-%m-%d')}\nAuthor: Auto-generated by Report Assistant")
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    add_page_break(doc)


def add_toc_placeholder(doc: Document):
    add_heading(doc, "Table of Contents", level=1)
    add_paragraph(doc, "Note: To update the Table of Contents, open this document in Microsoft Word and use References → Update Table.")
    # Provide a rough manual TOC for convenience
    add_bullets(doc, [
        "Executive Summary",
        "Project Overview",
        "Objectives and Scope",
        "System Architecture",
        "Key Modules and Components",
        "Database Design",
        "User Roles and Features",
        "Graphical User Interface (GUI)",
        "Command-Line Interface (CLI)",
        "Operational Workflows",
        "Installation and Setup",
        "Testing Strategy",
        "Security Considerations",
        "Performance and Reliability",
        "Risks and Mitigations",
        "Roadmap and Future Enhancements",
        "Non-functional Requirements",
        "Compliance and Licensing",
        "Extensibility and Customization",
        "Sample Use Cases",
        "Conclusion",
        "Appendix: Default Credentials and Paths",
    ])
    add_page_break(doc)


def section_executive_summary(doc: Document):
    add_heading(doc, "Executive Summary", level=1)
    add_paragraph(doc, (
        "The Disaster Relief Management System is a Python-based application designed to support end-to-end "
        "coordination of disaster relief operations. It enables affected citizens to submit emergency requests, "
        "volunteers to register with skills and availability, and administrators to triage requests, manage "
        "inventory, assign volunteers, and generate reports. The system uses SQLite for data persistence, "
        "Tkinter for a desktop GUI, and a modular design that also supports a CLI mode for environments without a GUI."
    ))
    add_paragraph(doc, (
        "This report provides a comprehensive overview of the system's objectives, scope, architecture, core "
        "modules, database schema, security posture, and operational workflows. It consolidates how the system "
        "is structured, how each role interacts with the platform, and how the platform can be extended and "
        "deployed."
    ))


def section_overview(doc: Document):
    add_heading(doc, "Project Overview", level=1)
    add_paragraph(doc, "Technology stack: Python 3.6+, Tkinter (GUI), SQLite (storage), standard library only.")
    add_paragraph(doc, (
        "The project adopts a clean, layered organization under the `src/disaster_relief/` package. Core logic lives "
        "in `core/` (database, authentication), presentation in `gui/` (Tkinter) and `cli/` (console), with helper "
        "scripts under `src/scripts/` for initialization and testing. Data is stored locally in `data/disaster_relief.db` "
        "to enable fully offline operation."
    ))
    add_bullets(doc, [
        "Offline-first: SQLite database, no external dependencies",
        "Role-based access: user, volunteer, admin",
        "Operational focus: request intake, triage, inventory, assignments, reporting",
        "Deploys easily on Windows/macOS/Linux with Python 3.6+",
    ])


def section_objectives_scope(doc: Document):
    add_heading(doc, "Objectives and Scope", level=1)
    add_paragraph(doc, "Primary objectives:", bold=True)
    add_bullets(doc, [
        "Provide a simple intake channel for disaster victims to request aid",
        "Maintain an up-to-date catalog of relief supplies and stock levels",
        "Register volunteers and track availability and skills",
        "Enable administrators to approve, assign, and track requests",
        "Offer reporting to monitor operational status and trends",
    ])
    add_paragraph(doc, "Out of scope in current version:", bold=True)
    add_bullets(doc, [
        "Multi-tenant or multi-organization workflows",
        "Geospatial routing and real-time logistics optimization",
        "Push notifications and external communications gateways",
        "Advanced RBAC beyond the three roles",
    ])


def section_architecture(doc: Document):
    add_heading(doc, "System Architecture", level=1)
    add_paragraph(doc, (
        "The system follows a modular architecture separating data, domain logic, and user interfaces. SQLite is used "
        "as the persistent store, accessed via a dedicated `DatabaseManager` that encapsulates schema management and "
        "CRUD operations. Authentication is handled by `AuthenticationManager`, which delegates to `DatabaseManager` "
        "for secure verification. The GUI layer presents an accessible desktop experience using Tkinter, while the CLI "
        "layer provides parity in headless environments."
    ))
    add_heading(doc, "Key Layers", level=2)
    add_bullets(doc, [
        "Data Layer: `core/database.py` (SQLite schema and operations)",
        "Auth Layer: `core/auth.py` (login, registration)",
        "GUI Layer: `gui/` (Tkinter windows and flows)",
        "CLI Layer: `cli/interfaces.py` (console flows)",
        "Scripts: `src/scripts/` for database init and system tests",
    ])
    add_paragraph(doc, (
        "The GUI entry point (`run_gui.py`) launches `gui/main_window.py`, which presents role-based dashboards. "
        "Requests and inventory are shown in rich tables with filtering and drill-down detail views. The CLI entry point "
        "(`run_cli.py`) launches a text-based workflow exposing the same core capabilities."
    ))


def section_modules(doc: Document):
    add_heading(doc, "Key Modules and Components", level=1)
    add_heading(doc, "Core", level=2)
    add_bullets(doc, [
        "`core/database.py` — database schema; user, volunteer, admin auth; CRUD for requests and inventory; assignments",
        "`core/auth.py` — session management and role retrieval; registration flows",
    ])
    add_heading(doc, "GUI", level=2)
    add_bullets(doc, [
        "`gui/main_window.py` — login/registration, role dashboards, navigation",
        "`gui/emergency_request_form.py` — intake form for user requests",
        "`gui/request_management.py` — admin/user/volunteer views of requests with status updates and assignment",
        "`gui/inventory_management.py` — manage stock, add/update items",
        "`gui/volunteer_management.py` — roster viewing and status (activation flow placeholder)",
        "`gui/reports.py` — dashboards summarizing requests, inventory, volunteers, high-priority items",
    ])
    add_heading(doc, "CLI", level=2)
    add_bullets(doc, [
        "`cli/interfaces.py` — console UI with login and role dashboards",
    ])


def section_database(doc: Document):
    add_heading(doc, "Database Design", level=1)
    add_paragraph(doc, (
        "SQLite backs the application with a schema oriented to requests, inventory, and volunteer management. All writes "
        "are parameterized to mitigate SQL injection risk, and passwords are SHA-256 hashed before persistence."
    ))

    # Table definitions overview
    add_heading(doc, "Tables Overview", level=2)

    # Users table
    add_heading(doc, "users", level=3)
    tbl = doc.add_table(rows=1, cols=3)
    hdr = tbl.rows[0].cells
    hdr[0].text = "Column"
    hdr[1].text = "Type"
    hdr[2].text = "Notes"
    rows = [
        ("id", "INTEGER", "PK AUTOINCREMENT"),
        ("username", "TEXT", "UNIQUE, NOT NULL"),
        ("email", "TEXT", "UNIQUE, NOT NULL"),
        ("password_hash", "TEXT", "NOT NULL, SHA-256"),
        ("emergency_type", "TEXT", "NOT NULL"),
        ("location", "TEXT", "NOT NULL"),
        ("contact_info", "TEXT", "NOT NULL"),
        ("created_at", "TIMESTAMP", "DEFAULT CURRENT_TIMESTAMP"),
    ]
    for c, t, n in rows:
        r = tbl.add_row().cells
        r[0].text, r[1].text, r[2].text = c, t, n

    add_paragraph(doc, " ")

    # Volunteers table
    add_heading(doc, "volunteers", level=3)
    tbl = doc.add_table(rows=1, cols=3)
    hdr = tbl.rows[0].cells
    hdr[0].text = "Column"
    hdr[1].text = "Type"
    hdr[2].text = "Notes"
    rows = [
        ("id", "INTEGER", "PK AUTOINCREMENT"),
        ("username", "TEXT", "UNIQUE, NOT NULL"),
        ("email", "TEXT", "UNIQUE, NOT NULL"),
        ("password_hash", "TEXT", "NOT NULL, SHA-256"),
        ("skills", "TEXT", "Comma-separated"),
        ("availability", "TEXT", "Textual schedule"),
        ("location", "TEXT", "NOT NULL"),
        ("contact_info", "TEXT", "NOT NULL"),
        ("status", "TEXT", "DEFAULT 'active'"),
        ("created_at", "TIMESTAMP", "DEFAULT CURRENT_TIMESTAMP"),
    ]
    for c, t, n in rows:
        r = tbl.add_row().cells
        r[0].text, r[1].text, r[2].text = c, t, n

    add_paragraph(doc, " ")

    # Admins table
    add_heading(doc, "admins", level=3)
    tbl = doc.add_table(rows=1, cols=3)
    hdr = tbl.rows[0].cells
    hdr[0].text = "Column"
    hdr[1].text = "Type"
    hdr[2].text = "Notes"
    rows = [
        ("id", "INTEGER", "PK AUTOINCREMENT"),
        ("username", "TEXT", "UNIQUE, NOT NULL"),
        ("email", "TEXT", "UNIQUE, NOT NULL"),
        ("password_hash", "TEXT", "NOT NULL, SHA-256"),
        ("role", "TEXT", "DEFAULT 'admin'"),
        ("created_at", "TIMESTAMP", "DEFAULT CURRENT_TIMESTAMP"),
    ]
    for c, t, n in rows:
        r = tbl.add_row().cells
        r[0].text, r[1].text, r[2].text = c, t, n

    add_paragraph(doc, " ")

    # Emergency requests
    add_heading(doc, "emergency_requests", level=3)
    tbl = doc.add_table(rows=1, cols=3)
    hdr = tbl.rows[0].cells
    hdr[0].text = "Column"
    hdr[1].text = "Type"
    hdr[2].text = "Notes"
    rows = [
        ("id", "INTEGER", "PK AUTOINCREMENT"),
        ("user_id", "INTEGER", "FK → users.id, NOT NULL"),
        ("request_type", "TEXT", "NOT NULL"),
        ("description", "TEXT", "NOT NULL"),
        ("priority", "TEXT", "DEFAULT 'medium'"),
        ("status", "TEXT", "DEFAULT 'pending'"),
        ("location", "TEXT", "NOT NULL"),
        ("contact_info", "TEXT", "NOT NULL"),
        ("created_at", "TIMESTAMP", "DEFAULT CURRENT_TIMESTAMP"),
        ("updated_at", "TIMESTAMP", "DEFAULT CURRENT_TIMESTAMP"),
        ("assigned_volunteer_id", "INTEGER", "FK → volunteers.id, nullable"),
        ("admin_notes", "TEXT", "Optional"),
    ]
    for c, t, n in rows:
        r = tbl.add_row().cells
        r[0].text, r[1].text, r[2].text = c, t, n

    add_paragraph(doc, " ")

    # Inventory
    add_heading(doc, "inventory", level=3)
    tbl = doc.add_table(rows=1, cols=3)
    hdr = tbl.rows[0].cells
    hdr[0].text = "Column"
    hdr[1].text = "Type"
    hdr[2].text = "Notes"
    rows = [
        ("id", "INTEGER", "PK AUTOINCREMENT"),
        ("item_name", "TEXT", "NOT NULL"),
        ("category", "TEXT", "NOT NULL"),
        ("quantity", "INTEGER", "NOT NULL"),
        ("unit", "TEXT", "NOT NULL"),
        ("location", "TEXT", "NOT NULL"),
        ("expiry_date", "DATE", "Optional"),
        ("status", "TEXT", "DEFAULT 'available'"),
        ("created_at", "TIMESTAMP", "DEFAULT CURRENT_TIMESTAMP"),
        ("updated_at", "TIMESTAMP", "DEFAULT CURRENT_TIMESTAMP"),
    ]
    for c, t, n in rows:
        r = tbl.add_row().cells
        r[0].text, r[1].text, r[2].text = c, t, n

    add_paragraph(doc, " ")

    # Supply requests
    add_heading(doc, "supply_requests", level=3)
    tbl = doc.add_table(rows=1, cols=3)
    hdr = tbl.rows[0].cells
    hdr[0].text = "Column"
    hdr[1].text = "Type"
    hdr[2].text = "Notes"
    rows = [
        ("id", "INTEGER", "PK AUTOINCREMENT"),
        ("emergency_request_id", "INTEGER", "FK → emergency_requests.id, NOT NULL"),
        ("inventory_id", "INTEGER", "FK → inventory.id, NOT NULL"),
        ("requested_quantity", "INTEGER", "NOT NULL"),
        ("allocated_quantity", "INTEGER", "DEFAULT 0"),
        ("status", "TEXT", "DEFAULT 'pending'"),
        ("created_at", "TIMESTAMP", "DEFAULT CURRENT_TIMESTAMP"),
    ]
    for c, t, n in rows:
        r = tbl.add_row().cells
        r[0].text, r[1].text, r[2].text = c, t, n

    add_paragraph(doc, (
        "Foreign keys logically link requests, inventory, and volunteers, providing traceability from intake to "
        "fulfillment and assignment."
    ))


def section_roles_features(doc: Document):
    add_heading(doc, "User Roles and Features", level=1)
    add_heading(doc, "Users (Disaster Victims)", level=2)
    add_bullets(doc, [
        "Register with emergency type, location, and contact details",
        "Submit emergency requests (type, description, priority)",
        "Track request status over time",
    ])
    add_heading(doc, "Volunteers", level=2)
    add_bullets(doc, [
        "Register with skills and availability",
        "View approved/in-progress requests suitable for assignment",
        "Respond to assignments (accept/reject)",
    ])
    add_heading(doc, "Administrators", level=2)
    add_bullets(doc, [
        "Triage and update request statuses (approve, reject, complete)",
        "Assign volunteers to requests and add admin notes",
        "Manage inventory (create/update items and quantities)",
        "Generate operational reports",
    ])


def section_gui(doc: Document):
    add_heading(doc, "Graphical User Interface (GUI)", level=1)
    add_paragraph(doc, (
        "The Tkinter GUI provides a clean, role-based experience with distinct dashboards. Core windows include "
        "login/registration, dashboards for each role, emergency request forms and listings, inventory management, "
        "volunteer management, and a reports hub. Tables support sorting and filtering by status, with modal dialogs "
        "for detailed views and actions such as approvals or assignments."
    ))
    add_bullets(doc, [
        "`main_window.py`: central navigation and role dashboards",
        "`emergency_request_form.py`: guided intake with priority and validation",
        "`request_management.py`: list, filter, approve/reject, and assign",
        "`inventory_management.py`: add items, update quantities, view details",
        "`volunteer_management.py`: view roster and statuses",
        "`reports.py`: summaries for requests, inventory, volunteers, and high priority items",
    ])


def section_cli(doc: Document):
    add_heading(doc, "Command-Line Interface (CLI)", level=1)
    add_paragraph(doc, (
        "The CLI mirrors the capabilities of the GUI for environments without a windowing system. Users authenticate, "
        "submit requests, and navigate menus. Administrators can browse requests, manage inventory, and view volunteer "
        "rosters."
    ))
    add_bullets(doc, [
        "Launch via `python run_cli.py`",
        "Modular design under `cli/interfaces.py`",
    ])


def section_workflows(doc: Document):
    add_heading(doc, "Operational Workflows", level=1)
    add_heading(doc, "Request Intake and Triage", level=2)
    add_numbered(doc, [
        "User submits a request (type, description, priority, location, contact)",
        "Admin reviews the request and sets status to approved or rejected",
        "Approved requests become visible to volunteers; admins may assign a volunteer",
        "Volunteer accepts assignment and proceeds to fulfill the request",
        "Admin marks request as completed with notes",
    ])
    add_heading(doc, "Inventory Lifecycle", level=2)
    add_numbered(doc, [
        "Admin adds or updates inventory items",
        "Requests may be paired with inventory via supply requests (future automation)",
        "Admins adjust quantities as stocks are allocated or replenished",
    ])


def section_setup(doc: Document):
    add_heading(doc, "Installation and Setup", level=1)
    add_bullets(doc, [
        "Prerequisites: Python 3.6+",
        "Initialize DB: `python src/scripts/init_database.py`",
        "Start GUI: `python run_gui.py`",
        "Start CLI: `python run_cli.py`",
        "Default admin: email `admin@disaster-relief.com`, password `admin123`",
    ])
    add_paragraph(doc, (
        "The application uses only the Python standard library, enabling quick setup and offline operation. The "
        "SQLite database auto-creates under `data/disaster_relief.db`."
    ))


def section_testing(doc: Document):
    add_heading(doc, "Testing Strategy", level=1)
    add_paragraph(doc, (
        "A lightweight test harness (`src/scripts/test_system.py`) validates database creation, admin authentication, "
        "inventory retrieval, and emergency requests endpoints. This can serve as a foundation for a broader suite "
        "including unit tests for the data layer and UI smoke tests."
    ))
    add_bullets(doc, [
        "Run: `python src/scripts/test_system.py`",
        "Extend: add unit tests per module; consider pytest for richer assertions",
    ])


def section_security(doc: Document):
    add_heading(doc, "Security Considerations", level=1)
    add_bullets(doc, [
        "Credential handling: SHA-256 password hashing",
        "SQL safety: parameterized queries for all writes",
        "RBAC: role detection and role-specific views/actions",
    ])
    add_paragraph(doc, (
        "Further hardening can include password policies, account lockouts, role auditing, and migration from SHA-256 "
        "to a password hashing scheme with per-user salts and work factors (e.g., bcrypt/argon2)."
    ))


def section_performance(doc: Document):
    add_heading(doc, "Performance and Reliability", level=1)
    add_bullets(doc, [
        "Local SQLite database for low-latency operations",
        "Lightweight GUI with incremental data rendering",
        "Minimal resource footprint; suitable for low-power devices",
    ])
    add_paragraph(doc, (
        "For larger-scale deployments, consider transitioning to a client/server architecture with a network database "
        "(PostgreSQL), connection pooling, and a REST or gRPC API to support many concurrent clients."
    ))


def section_risks(doc: Document):
    add_heading(doc, "Risks and Mitigations", level=1)
    add_bullets(doc, [
        "Single-node storage: backups are essential (automate DB backups)",
        "Credential hashing: migrate to stronger schemes with salts",
        "UI safety: input validation is present; continue to sanitize and constrain",
        "Volunteer status flows: ensure assignment acceptance/rejection flows are visible and auditable",
    ])


def section_roadmap(doc: Document):
    add_heading(doc, "Roadmap and Future Enhancements", level=1)
    add_bullets(doc, [
        "Introduce per-user salted password hashing (bcrypt/argon2)",
        "Volunteer shift scheduling and geolocation matching",
        "Automated allocation between requests and inventory (supply planning)",
        "Exportable reports (CSV/PDF), and notification integrations",
        "Multi-user sync via a central API server and Postgres backend",
    ])


def section_nfr(doc: Document):
    add_heading(doc, "Non-functional Requirements", level=1)
    add_bullets(doc, [
        "Availability: offline-capable; start within 2 seconds on modern hardware",
        "Usability: clear role-based navigation and accessible forms",
        "Maintainability: modular code with clear separation by layer",
        "Portability: runs on Windows/macOS/Linux with Python 3.6+",
        "Security: hashed credentials, parameterized SQL, least-privilege UI",
    ])


def section_compliance(doc: Document):
    add_heading(doc, "Compliance and Licensing", level=1)
    add_paragraph(doc, (
        "The project is open source under the MIT License, enabling broad use and modification with attribution. "
        "Operational deployments should evaluate data protection policies and, if collecting personally identifiable "
        "information (PII), enforce relevant regulations and retention policies."
    ))


def section_extensibility(doc: Document):
    add_heading(doc, "Extensibility and Customization", level=1)
    add_bullets(doc, [
        "Add database operations in `core/database.py`",
        "Extend authentication in `core/auth.py`",
        "Add UI screens under `gui/` or CLI flows under `cli/`",
        "Bundle scripts and installers via `setup.py` or platform-native packagers",
    ])


def section_use_cases(doc: Document):
    add_heading(doc, "Sample Use Cases", level=1)
    add_heading(doc, "Rapid Intake During Flooding", level=2)
    add_paragraph(doc, (
        "Local authorities deploy the app on laptops at community centers. Victims register and submit requests for "
        "shelter and medical supplies. Admins approve and assign volunteers based on proximity and skills while "
        "monitoring inventory of tents and first-aid kits."
    ))
    add_heading(doc, "Offline Field Operations", level=2)
    add_paragraph(doc, (
        "Volunteers operate in regions without connectivity. The offline database allows full operation; at the end of "
        "the day, database files are synchronized back to a central hub for aggregation and reporting."
    ))


def section_conclusion(doc: Document):
    add_heading(doc, "Conclusion", level=1)
    add_paragraph(doc, (
        "The Disaster Relief Management System provides a pragmatic, offline-first toolset for managing the essential "
        "workflows of relief operations: capturing requests, coordinating volunteers, and tracking inventory. Its "
        "simple deployment model and modular codebase make it suitable for rapid rollouts and local customizations, "
        "with clear pathways to scale and harden for larger deployments."
    ))


def section_appendix(doc: Document):
    add_heading(doc, "Appendix: Default Credentials and Paths", level=1)
    add_bullets(doc, [
        "Default admin email: admin@disaster-relief.com",
        "Default admin password: admin123",
        "Database path: data/disaster_relief.db",
        "Test harness: src/scripts/test_system.py",
        "DB init: src/scripts/init_database.py",
    ])


def build_report():
    doc = Document()

    # Basic styles
    styles = doc.styles
    styles['Normal'].font.name = 'Calibri'
    styles['Normal'].font.size = Pt(11)

    add_header_footer(doc)
    add_cover_page(doc)
    add_toc_placeholder(doc)

    section_executive_summary(doc)
    section_overview(doc)
    section_objectives_scope(doc)
    section_architecture(doc)
    section_modules(doc)
    section_database(doc)
    section_roles_features(doc)
    section_gui(doc)
    section_cli(doc)
    section_workflows(doc)
    section_setup(doc)
    section_testing(doc)
    section_security(doc)
    section_performance(doc)
    section_risks(doc)
    section_roadmap(doc)
    section_nfr(doc)
    section_compliance(doc)
    section_extensibility(doc)
    section_use_cases(doc)
    section_conclusion(doc)
    section_appendix(doc)

    doc.save(OUTPUT_PATH)
    return OUTPUT_PATH


if __name__ == "__main__":
    path = build_report()
    print(f"Report generated: {path}")
